# Use the latest 2.1 version of CircleCI pipeline processing engine, see https://circleci.com/docs/2.0/configuration-reference/
version: 2.1

executors:
  default:
    machine:
      image: ubuntu-1604:201903-01
      docker_layer_caching: true
    working_directory: /home/circleci/.go_workspace/src/github.com/mookjp/yakiire
  container:
    docker:
      - image: golang
    working_directory: /go/src/github.com/mookjp/yakiire

jobs:
  build:
    executor: default
    steps:
      - checkout
      - restore_cache:
          keys:
            - vendor-{{ checksum "Gopkg.lock" }}
      - run:
          name: Install dependencies
          command: |
            if [ ! -d vendor ]; then
              make dep
            fi
      - run:
          name: Build
          command: |
            make build
      - save_cache:
          key: vendor-{{ checksum "Gopkg.lock" }}
          paths:
            - vendor
      - persist_to_workspace:
          root: /home/circleci/.go_workspace/src/github.com/mookjp/yakiire
          paths:
            - "bin/yakiire" # to get the version in release job
            - "vendor/*"
  lint:
    executor: container
    steps:
      - checkout
      - restore_cache:
          keys:
            - vendor-{{ checksum "Gopkg.lock" }}
      - run:
          name: Install tools
          command: |
            make bootstrap-lint-tools
      - run:
          name: Install dependencies
          command: |
            if [ ! -d vendor ]; then
              make dep
            fi
      - run:
          name: Lint
          command: |
            make lint
      - save_cache:
          key: vendor-{{ checksum "Gopkg.lock" }}
          paths:
            - vendor
  test:
    executor: default
    steps:
      - checkout
      - attach_workspace:
          at: /home/circleci/.go_workspace/src/github.com/mookjp/yakiire
      - run:
          name: Run tests
          command: |
            make test
  release:
    executor: default
    steps:
      - checkout
      - attach_workspace:
          at: /home/circleci/.go_workspace/src/github.com/mookjp/yakiire
      - run:
          name: Get tools
          command: |
            go get github.com/mitchellh/gox
            go get github.com/tcnksm/ghr
      - run:
          name: Compile
          command: |
            mkdir dist
            gox -osarch="linux/386 linux/amd64 darwin/amd64 darwin/386 windows/386 windows/amd64" -output="dist/{{.OS}}_{{.Arch}}/{{.Dir}}"
            ls dist | xargs -ITARGET zip -r dist/TARGET dist/TARGET
      - run:
          name: Upload binary
          command: |
              ghr -t ${GITHUB_TOKEN} \
                -u ${CIRCLE_PROJECT_USERNAME} \
                -r ${CIRCLE_PROJECT_REPONAME} \
                -c ${CIRCLE_SHA1} \
                -n $(./bin/yakiire --version) \
                -delete \
                -prerelease \
                $(./bin/yakiire --version) \
                dist

workflows:
  version: 2.1
  default:
    jobs:
      - build
      - lint:
          requires:
            - build
      - test:
          requires:
            - build
      - release:
          requires:
            - lint
            - test
          filters:
            branches:
              only:
                - master
                - develop
